<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>ir.artanpg.boot</groupId>
    <artifactId>artan-boot-dependencies</artifactId>
    <version>${revision}</version>
    <relativePath>../../artan-boot-platforms/artan-boot-dependencies</relativePath>
  </parent>

  <artifactId>artan-boot-starter-parent</artifactId>
  <packaging>pom</packaging>

  <name>artan-boot-starter-parent</name>
  <description>Parent pom providing dependency and plugin management for applications built with Maven</description>

  <properties>
    <java.version>21</java.version>
    <resource.delimiter>@</resource.delimiter>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

    <main.basedir>${basedir}/../..</main.basedir>

    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <maven.compiler.failOnWarning>false</maven.compiler.failOnWarning>
  </properties>

  <build>
    <resources>
      <resource>
        <directory>${basedir}/src/main/resources</directory>
        <filtering>true</filtering>
        <includes>
          <include>**/application*.yml</include>
          <include>**/application*.yaml</include>
          <include>**/application*.properties</include>
        </includes>
        <excludes>
          <exclude>excludes/**</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${basedir}/src/main/resources</directory>
        <excludes>
          <exclude>**/application*.yml</exclude>
          <exclude>**/application*.yaml</exclude>
          <exclude>**/application*.properties</exclude>
          <exclude>excludes/**</exclude>
        </excludes>
      </resource>
    </resources>

    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <configuration>
            <source>${java.version}</source>
            <target>${java.version}</target>
            <release>${java.version}</release>
            <parameters>true</parameters>
            <showWarnings>true</showWarnings>
            <enablePreview>true</enablePreview>
            <encoding>${project.build.sourceEncoding}</encoding>
            <failOnWarning>${maven.compiler.failOnWarning}</failOnWarning>
            <compilerArgs>
              <arg>-Xlint:cast</arg>
              <arg>-Xlint:serial</arg>
              <arg>-Xlint:removal</arg>
              <arg>-Xlint:unchecked</arg>
              <arg>-Xlint:deprecation</arg>
            </compilerArgs>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <configuration>
            <propertiesEncoding>${project.build.sourceEncoding}</propertiesEncoding>
            <delimiters>
              <delimiter>${resource.delimiter}</delimiter>
            </delimiters>
            <useDefaultDelimiters>false</useDefaultDelimiters>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <configuration>
            <archive>
              <manifest>
                <!--suppress UnresolvedMavenProperty -->
                <mainClass>${start-class}</mainClass>
                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
              </manifest>
            </archive>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-war-plugin</artifactId>
          <configuration>
            <archive>
              <manifest>
                <!--suppress UnresolvedMavenProperty -->
                <mainClass>${start-class}</mainClass>
                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
              </manifest>
            </archive>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-enforcer-plugin</artifactId>
          <executions>
            <execution>
              <id>enforce-release</id>
              <phase>compile</phase>
              <goals>
                <goal>enforce</goal>
              </goals>
              <configuration>
                <rules>
                  <requireMavenVersion>
                    <version>[3.9.0,)</version>
                    <message>Maven version 3.9.0 or higher is required to compile the project.</message>
                  </requireMavenVersion>
                  <requireJavaVersion>
                    <version>[21,)</version>
                    <message>Java version 21 or higher is required to compile the project.</message>
                  </requireJavaVersion>
                </rules>
              </configuration>
            </execution>
          </executions>
        </plugin>

        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
          <version>${spring-boot.version}</version>
          <executions>
            <execution>
              <id>repackage</id>
              <goals>
                <goal>repackage</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <!--suppress UnresolvedMavenProperty -->
            <mainClass>${start-class}</mainClass>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <inherited>false</inherited>
        <executions>
          <execution>
            <!-- Flatten and simplify our own POM for install/deploy -->
            <id>flatten</id>
            <phase>process-resources</phase>
            <goals>
              <goal>flatten</goal>
            </goals>
            <configuration>
              <updatePomFile>true</updatePomFile>
              <pomElements>
                <parent>expand</parent>
                <name>keep</name>
                <description>keep</description>
                <url>expand</url>
                <properties>keep</properties>
                <pluginManagement>keep</pluginManagement>
                <dependencyManagement>keep</dependencyManagement>
                <build>keep</build>
                <profiles>keep</profiles>
              </pomElements>
            </configuration>
          </execution>
          <execution>
            <id>flatten-clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>xml-maven-plugin</artifactId>
        <inherited>false</inherited>
        <executions>
          <execution>
            <!-- Cleanup the flattened project POM -->
            <id>post-process-flattened-pom</id>
            <phase>process-resources</phase>
            <goals>
              <goal>transform</goal>
            </goals>
            <configuration>
              <transformationSets>
                <transformationSet>
                  <dir>${project.basedir}</dir>
                  <outputDir>${project.basedir}</outputDir>
                  <includes>.flattened-pom.xml</includes>
                  <stylesheet>src/main/xslt/post-process-flattened-pom.xsl</stylesheet>
                  <outputProperties>
                    <outputProperty>
                      <name>indent</name>
                      <value>yes</value>
                    </outputProperty>
                  </outputProperties>
                </transformationSet>
              </transformationSets>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>documentation</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
            <executions>
              <execution>
                <id>attach-sources</id>
                <phase>package</phase>
                <goals>
                  <goal>jar-no-fork</goal>
                </goals>
              </execution>
            </executions>
            <inherited>true</inherited>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <configuration>
              <source>${java.version}</source>
              <excludePackageNames>**/target/generated/**/*.java</excludePackageNames>
              <excludePackageNames>**/target/generated-sources/**/*.java</excludePackageNames>
              <sourcepath>src/main/java</sourcepath>
            </configuration>
            <executions>
              <execution>
                <id>attach-javadocs</id>
                <phase>package</phase>
                <goals>
                  <goal>jar</goal>
                </goals>
              </execution>
            </executions>
            <inherited>true</inherited>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>format</id>
      <properties>
        <checkstyle.failsOnError>true</checkstyle.failsOnError>
        <checkstyle.failOnViolation>true</checkstyle.failOnViolation>
        <checkstyle.include.test.source>true</checkstyle.include.test.source>
        <checkstyle.include.test.resources>false</checkstyle.include.test.resources>
        <checkstyle.excludes>${project.build.directory}</checkstyle.excludes>
      </properties>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-enforcer-plugin</artifactId>
            <executions>
              <execution>
                <id>enforce-checkstyle-config</id>
                <phase>process-sources</phase>
                <goals>
                  <goal>enforce</goal>
                </goals>
                <configuration>
                  <rules>
                    <requireProperty>
                      <property>checkstyle.config.location</property>
                      <message>Property 'checkstyle.config.location' must be set for this build!</message>
                    </requireProperty>
                    <requireProperty>
                      <property>checkstyle.properties.location</property>
                      <message>Property 'checkstyle.properties.location' must be set for this build!</message>
                    </requireProperty>
                    <requireProperty>
                      <property>checkstyle.suppressions.location</property>
                      <message>Property 'checkstyle.suppressions.location' must be set for this build!</message>
                    </requireProperty>
                  </rules>
                  <fail>true</fail>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-checkstyle-plugin</artifactId>
            <executions>
              <execution>
                <id>checkstyle</id>
                <phase>process-sources</phase>
                <goals>
                  <goal>check</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <consoleOutput>true</consoleOutput>
              <failsOnError>${checkstyle.failsOnError}</failsOnError>
              <failOnViolation>${checkstyle.failOnViolation}</failOnViolation>
              <propertyExpansion>
                project.groupId=${project.groupId}
              </propertyExpansion>
              <!--suppress UnresolvedMavenProperty -->
              <configLocation>${checkstyle.config.location}</configLocation>
              <!--suppress UnresolvedMavenProperty -->
              <propertiesLocation>${checkstyle.properties.location}</propertiesLocation>
              <!--suppress UnresolvedMavenProperty -->
              <suppressionsLocation>${checkstyle.suppressions.location}</suppressionsLocation>
              <excludes>${checkstyle.excludes}</excludes>
              <includeTestSourceDirectory>${checkstyle.include.test.source}</includeTestSourceDirectory>
              <includeTestResources>${checkstyle.include.test.resources}</includeTestResources>
            </configuration>
            <dependencies>
              <dependency>
                <groupId>com.puppycrawl.tools</groupId>
                <artifactId>checkstyle</artifactId>
                <version>${checkstyle.version}</version>
              </dependency>
              <dependency>
                <groupId>io.spring.javaformat</groupId>
                <artifactId>spring-javaformat-checkstyle</artifactId>
                <version>${spring-javaformat-checkstyle.version}</version>
              </dependency>
            </dependencies>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>execute-tests</id>
      <properties>
        <surefire.argLine/>
        <failsafe.argLine/>
        <maven.test.skip>false</maven.test.skip>
        <jacoco.includes/>
        <jacoco.excludes/>
        <jacoco.report.title>${project.name}</jacoco.report.title>
        <jacoco.report.footer>${project.name}</jacoco.report.footer>
        <jacoco.report.formats>HTML</jacoco.report.formats>
        <jacoco.report.outputDirectory>${project.reporting.outputDirectory}/jacoco</jacoco.report.outputDirectory>
        <jacoco.rule.bundle.complexity.ratio>0.95</jacoco.rule.bundle.complexity.ratio>
        <jacoco.rule.bundle.branch.ratio>1</jacoco.rule.bundle.branch.ratio>
        <jacoco.rule.bundle.line.ratio>0.80</jacoco.rule.bundle.line.ratio>
        <jacoco.rule.class.line.ratio>0.80</jacoco.rule.class.line.ratio>
        <jacoco.rule.class.method.ratio>0.80</jacoco.rule.class.method.ratio>
      </properties>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <configuration>
              <argLine>
                @{surefire.argLine}
                -javaagent:${settings.localRepository}/net/bytebuddy/byte-buddy-agent/${byte-buddy.version}/byte-buddy-agent-${byte-buddy.version}.jar
                -javaagent:${settings.localRepository}/org/mockito/mockito-core/${mockito.version}/mockito-core-${mockito.version}.jar
              </argLine>
              <includes>
                <include>**/*Tests.java</include>
              </includes>
              <excludes>
                <exclude>**/Abstract*.java</exclude>
                <exclude>**/*IT.java</exclude>
                <exclude>**/*IntegrationTests.java</exclude>
              </excludes>
              <parallel>methods</parallel>
              <threadCount>10</threadCount>
              <perCoreThreadCount>false</perCoreThreadCount>
              <useModulePath>false</useModulePath>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-failsafe-plugin</artifactId>
            <executions>
              <execution>
                <id>integration-test</id>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <argLine>
                @{failsafe.argLine}
                -javaagent:${settings.localRepository}/net/bytebuddy/byte-buddy-agent/${byte-buddy.version}/byte-buddy-agent-${byte-buddy.version}.jar
                -javaagent:${settings.localRepository}/org/mockito/mockito-core/${mockito.version}/mockito-core-${mockito.version}.jar
              </argLine>
              <includes>
                <include>**/*IntegrationTests.java</include>
                <include>**/*IT.java</include>
              </includes>
              <excludes>
                <exclude>**/*Tests.java</exclude>
                <exclude>**/Abstract*.java</exclude>
              </excludes>
              <parallel>methods</parallel>
              <threadCount>10</threadCount>
              <perCoreThreadCount>false</perCoreThreadCount>
              <useModulePath>false</useModulePath>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
            <configuration>
              <includes>
                <include>${jacoco.includes}</include>
              </includes>
              <excludes>
                <exclude>${jacoco.excludes}</exclude>
                <exclude>**/*_.class</exclude>
                <exclude>**/*$*.class</exclude>
                <exclude>**/config/**/*.class</exclude>
                <exclude>**/dto/**/*.class</exclude>
                <exclude>**/command/**/*.class</exclude>
                <exclude>**/entity/**/*.class</exclude>
                <exclude>**/*Application.class</exclude>
                <exclude>**/module-info.class</exclude>
              </excludes>
            </configuration>
            <executions>
              <!-- Unit Test Coverage -->
              <execution>
                <id>jacoco-prepare-initialize</id>
                <phase>initialize</phase>
                <goals>
                  <goal>prepare-agent</goal>
                </goals>
                <configuration>
                  <propertyName>surefire.argLine</propertyName>
                </configuration>
              </execution>
              <!-- Integration Test Coverage -->
              <execution>
                <id>jacoco-prepare-integration-initialize</id>
                <phase>pre-integration-test</phase>
                <goals>
                  <goal>prepare-agent-integration</goal>
                </goals>
                <configuration>
                  <propertyName>failsafe.argLine</propertyName>
                </configuration>
              </execution>
              <!-- Check Coverage Rules -->
              <execution>
                <id>default-check</id>
                <phase>verify</phase>
                <goals>
                  <goal>check</goal>
                </goals>
                <configuration>
                  <rules>
                    <!-- The main rule for the entire project -->
                    <rule>
                      <element>BUNDLE</element>
                      <excludes>
                        <exclude>**/utils/**</exclude>
                      </excludes>
                      <limits>
                        <limit>
                          <counter>COMPLEXITY</counter>
                          <value>COVEREDRATIO</value>
                          <minimum>${jacoco.rule.bundle.complexity.ratio}</minimum>
                        </limit>
                        <limit>
                          <counter>BRANCH</counter>
                          <value>COVEREDRATIO</value>
                          <minimum>${jacoco.rule.bundle.branch.ratio}</minimum>
                        </limit>
                        <limit>
                          <counter>LINE</counter>
                          <value>COVEREDRATIO</value>
                          <minimum>${jacoco.rule.bundle.line.ratio}</minimum>
                        </limit>
                      </limits>
                    </rule>
                    <!-- Separate rule for Utility classes -->
                    <rule>
                      <element>CLASS</element>
                      <includes>
                        <include>**/utils/**</include>
                      </includes>
                      <limits>
                        <limit>
                          <counter>LINE</counter>
                          <value>COVEREDRATIO</value>
                          <minimum>${jacoco.rule.class.line.ratio}</minimum>
                        </limit>
                        <limit>
                          <counter>METHOD</counter>
                          <value>COVEREDRATIO</value>
                          <minimum>${jacoco.rule.class.method.ratio}</minimum>
                        </limit>
                      </limits>
                    </rule>
                  </rules>
                </configuration>
              </execution>
              <!-- Generate Reports -->
              <execution>
                <id>jacoco-report</id>
                <phase>verify</phase>
                <goals>
                  <goal>report</goal>
                  <goal>report-integration</goal>
                </goals>
                <configuration>
                  <outputDirectory>${jacoco.report.outputDirectory}</outputDirectory>
                  <title>${jacoco.report.title}</title>
                  <footer>${jacoco.report.footer}</footer>
                  <formats>
                    <format>${jacoco.report.formats}</format>
                  </formats>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>native</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-jar-plugin</artifactId>
            <configuration>
              <archive>
                <manifestEntries>
                  <Spring-Boot-Native-Processed>true</Spring-Boot-Native-Processed>
                </manifestEntries>
              </archive>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>process-aot</id>
                <goals>
                  <goal>process-aot</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.graalvm.buildtools</groupId>
            <artifactId>native-maven-plugin</artifactId>
            <configuration>
              <classesDirectory>${project.build.outputDirectory}</classesDirectory>
              <exclusions>
                <exclusion>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-devtools</artifactId>
                </exclusion>
              </exclusions>
            </configuration>
            <executions>
              <execution>
                <id>add-reachability-metadata</id>
                <goals>
                  <goal>add-reachability-metadata</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>nativeTest</id>
      <dependencies>
        <dependency>
          <groupId>org.junit.platform</groupId>
          <artifactId>junit-platform-launcher</artifactId>
          <scope>test</scope>
        </dependency>
      </dependencies>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.springframework.boot</groupId>
              <artifactId>spring-boot-maven-plugin</artifactId>
              <executions>
                <execution>
                  <id>process-test-aot</id>
                  <goals>
                    <goal>process-test-aot</goal>
                  </goals>
                </execution>
              </executions>
            </plugin>
            <plugin>
              <groupId>org.graalvm.buildtools</groupId>
              <artifactId>native-maven-plugin</artifactId>
              <configuration>
                <classesDirectory>${project.build.outputDirectory}</classesDirectory>
                <exclusions>
                  <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-devtools</artifactId>
                  </exclusion>
                </exclusions>
              </configuration>
              <executions>
                <execution>
                  <id>native-test</id>
                  <goals>
                    <goal>test</goal>
                  </goals>
                </execution>
              </executions>
            </plugin>
          </plugins>
        </pluginManagement>
      </build>
    </profile>
  </profiles>
</project>
