<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>ir.artanpg.boot</groupId>
    <artifactId>artan-boot-parent</artifactId>
    <version>${revision}</version>
    <relativePath>../artan-boot-platforms/artan-boot-parent</relativePath>
  </parent>

  <artifactId>artan-boot-core</artifactId>
  <packaging>pom</packaging>

  <name>artan-boot-core</name>
  <description>Artan Core Module</description>

  <properties>
    <main.basedir>${basedir}/..</main.basedir>
  </properties>

  <modules>
    <module>artan-boot-domain</module>
    <module>artan-boot-application</module>
    <module>artan-boot-infrastructure</module>
  </modules>
</project>
