<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>ir.artanpg.boot</groupId>
    <artifactId>artan-boot-builder</artifactId>
    <version>${revision}</version>
  </parent>

  <artifactId>artan-boot-platforms</artifactId>
  <packaging>pom</packaging>

  <name>artan-boot-platforms</name>
  <description>Artan Platforms Module</description>

  <properties>
    <main.basedir>${basedir}/..</main.basedir>
  </properties>

  <modules>
    <module>artan-boot-dependencies</module>
    <module>artan-boot-parent</module>
  </modules>
</project>
