<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>ir.artanpg.boot</groupId>
    <artifactId>artan-boot-dependencies</artifactId>
    <version>${revision}</version>
    <relativePath>../artan-boot-dependencies</relativePath>
  </parent>

  <artifactId>artan-boot-parent</artifactId>
  <packaging>pom</packaging>

  <name>artan-boot-parent</name>
  <description>Parent module for all modules in this project.</description>

  <properties>
    <main.basedir>${basedir}/../..</main.basedir>

    <argLine>-Xmx2048m</argLine>
    <threadCount>10</threadCount>
  </properties>

  <build>
    <resources>
      <resource>
        <directory>${basedir}/src/main/resources</directory>
        <filtering>true</filtering>
        <excludes>
          <exclude>excludes/**</exclude>
        </excludes>
      </resource>
    </resources>
    <testResources>
      <testResource>
        <directory>${basedir}/src/test/resources</directory>
        <filtering>true</filtering>
        <excludes>
          <exclude>excludes/**</exclude>
        </excludes>
      </testResource>
    </testResources>

    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <inherited>true</inherited>
          <configuration>
            <source>${java.version}</source>
            <target>${java.version}</target>
            <release>${java.version}</release>
            <parameters>true</parameters>
            <enablePreview>true</enablePreview>
            <showWarnings>true</showWarnings>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <inherited>true</inherited>
          <configuration>
            <archive>
              <manifest>
                <addDefaultSpecificationEntries>false</addDefaultSpecificationEntries>
                <addDefaultImplementationEntries>false</addDefaultImplementationEntries>
              </manifest>
              <manifestEntries>
                <Built-By>Artan Programming Group</Built-By>
                <Implementation-Name>${project.name}</Implementation-Name>
                <Implementation-Description>${project.description}</Implementation-Description>
                <Implementation-Version>${project.version}</Implementation-Version>
              </manifestEntries>
            </archive>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <executions>
            <execution>
              <id>unit-test</id>
              <goals>
                <goal>test</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <includes>
              <include>**/*Tests.java</include>
            </includes>
            <excludes>
              <exclude>**/Abstract*.java</exclude>
            </excludes>
            <parallel>methods</parallel>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-failsafe-plugin</artifactId>
          <executions>
            <execution>
              <goals>
                <goal>integration-test</goal>
                <goal>verify</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <includes>
              <include>**/*IntegrationTests.java</include>
            </includes>
            <excludes>
              <exclude>**/*Tests.java</exclude>
              <exclude>**/Abstract*.java</exclude>
            </excludes>
            <parallel>methods</parallel>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-enforcer-plugin</artifactId>
          <executions>
            <execution>
              <id>enforce-rules</id>
              <goals>
                <goal>enforce</goal>
              </goals>
              <configuration>
                <rules>
                  <requireJavaVersion>
                    <version>[21,)</version>
                    <message>Java version 21 or higher is required to compile the project.</message>
                  </requireJavaVersion>
                  <requireMavenVersion>
                    <version>[3.9.0,)</version>
                    <message>Maven version 3.9.0 or higher is required to compile the project.</message>
                  </requireMavenVersion>
                  <requireProperty>
                    <property>main.basedir</property>
                  </requireProperty>
                  <requireProperty>
                    <property>project.name</property>
                  </requireProperty>
                  <requireProperty>
                    <property>project.description</property>
                  </requireProperty>
                  <requireReleaseDeps>
                    <onlyWhenRelease>true</onlyWhenRelease>
                  </requireReleaseDeps>
                </rules>
                <fail>true</fail>
              </configuration>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>flatten-maven-plugin</artifactId>
          <inherited>true</inherited>
          <executions>
            <execution>
              <id>flatten</id>
              <phase>process-resources</phase>
              <goals>
                <goal>flatten</goal>
              </goals>
              <configuration>
                <updatePomFile>true</updatePomFile>
                <flattenMode>oss</flattenMode>
                <pomElements>
                  <parent>expand</parent>
                  <distributionManagement>remove</distributionManagement>
                  <repositories>remove</repositories>
                </pomElements>
              </configuration>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
