<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>ir.artanpg.boot</groupId>
		<artifactId>artan-boot-dependencies</artifactId>
		<version>0.0.0-SNAPSHOT</version>
		<relativePath>../artan-boot-dependencies</relativePath>
	</parent>

	<artifactId>artan-boot-parent</artifactId>
	<packaging>pom</packaging>

	<name>artan-boot-parent</name>
	<description>Parent module for all modules in this project.</description>

	<properties>
		<argLine>-Xmx2048m</argLine>
		<threadCount>10</threadCount>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.platform</groupId>
					<artifactId>junit-platform-commons</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-params</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.jupiter</groupId>
					<artifactId>junit-jupiter-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apiguardian</groupId>
					<artifactId>apiguardian-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jspecify</groupId>
					<artifactId>jspecify</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.jupiter</groupId>
					<artifactId>junit-jupiter-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apiguardian</groupId>
					<artifactId>apiguardian-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jspecify</groupId>
					<artifactId>jspecify</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.opentest4j</groupId>
					<artifactId>opentest4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-console</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.apiguardian</groupId>
					<artifactId>apiguardian-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jspecify</groupId>
					<artifactId>jspecify</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.junit.platform</groupId>
					<artifactId>junit-platform-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<defaultGoal>clean install</defaultGoal>

		<resources>
			<resource>
				<directory>${basedir}/src/main/resources</directory>
				<filtering>true</filtering>
				<excludes>
					<exclude>excludes/**</exclude>
				</excludes>
			</resource>
		</resources>
		<testResources>
			<testResource>
				<directory>${basedir}/src/test/resources</directory>
				<filtering>true</filtering>
				<excludes>
					<exclude>excludes/**</exclude>
				</excludes>
			</testResource>
		</testResources>

		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven-compiler-plugin.version}</version>
					<inherited>true</inherited>
					<configuration>
						<source>${java.version}</source>
						<target>${java.version}</target>
						<release>${java.version}</release>
						<parameters>true</parameters>
						<enablePreview>true</enablePreview>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>${maven-jar-plugin.version}</version>
					<inherited>true</inherited>
					<configuration>
						<archive>
							<addMavenDescriptor>false</addMavenDescriptor>
							<manifest>
								<addDefaultSpecificationEntries>false</addDefaultSpecificationEntries>
								<addDefaultImplementationEntries>false</addDefaultImplementationEntries>
							</manifest>
							<manifestEntries>
								<Built-By>Artan Programming Group</Built-By>
								<Implementation-Title>${project.name}</Implementation-Title>
								<Implementation-Version>${project.version}</Implementation-Version>
							</manifestEntries>
						</archive>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-source-plugin</artifactId>
					<version>${maven-source-plugin.version}</version>
					<inherited>true</inherited>
					<executions>
						<execution>
							<id>attach-sources</id>
							<phase>package</phase>
							<goals>
								<goal>jar-no-fork</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<version>${maven-javadoc-plugin.version}</version>
					<inherited>true</inherited>
					<configuration>
						<source>${java.version}</source>
					</configuration>
					<executions>
						<execution>
							<id>attach-javadocs</id>
							<phase>package</phase>
							<goals>
								<goal>jar</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>${maven-surefire-plugin.version}</version>
					<inherited>true</inherited>
					<executions>
						<execution>
							<id>unit-test</id>
							<goals>
								<goal>test</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
						<runOrder>alphabetical</runOrder>
						<includes>
							<include>**/*Tests.java</include>
						</includes>
						<excludes>
							<exclude>**/Abstract*.java</exclude>
						</excludes>
						<parallel>methods</parallel>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-enforcer-plugin</artifactId>
					<version>${maven-enforcer-plugin.version}</version>
					<inherited>true</inherited>
					<executions>
						<execution>
							<id>enforce-release</id>
							<goals>
								<goal>enforce</goal>
							</goals>
							<phase>validate</phase>
							<configuration>
								<rules>
									<requireJavaVersion>
										<version>[21,)</version>
										<message>At least your java version should be 21 !!!</message>
									</requireJavaVersion>
									<requireMavenVersion>
										<version>[3.9.0,)</version>
										<message>At least your maven version should be 3.9.0 or higher !!!</message>
									</requireMavenVersion>
									<banDuplicatePomDependencyVersions>
										<message>No duplicate dependencies allowed !!!</message>
									</banDuplicatePomDependencyVersions>
									<requireProperty>
										<property>project.name</property>
									</requireProperty>
									<requireProperty>
										<property>project.description</property>
									</requireProperty>
								</rules>
								<fail>true</fail>
							</configuration>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>flatten-maven-plugin</artifactId>
					<version>${flatten-maven-plugin.version}</version>
					<inherited>true</inherited>
					<executions>
						<execution>
							<!-- Tidy up all POMs before they are published -->
							<id>flatten</id>
							<phase>process-resources</phase>
							<goals>
								<goal>flatten</goal>
							</goals>
							<configuration>
								<updatePomFile>true</updatePomFile>
								<flattenMode>oss</flattenMode>
								<pomElements>
									<scm>remove</scm>
									<issueManagement>remove</issueManagement>
									<distributionManagement>remove</distributionManagement>
									<repositories>remove</repositories>
								</pomElements>
							</configuration>
						</execution>
						<execution>
							<id>flatten-clean</id>
							<phase>clean</phase>
							<goals>
								<goal>clean</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</pluginManagement>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>execute-tests</id>

			<properties>
				<maven.test.skip>false</maven.test.skip>

				<!-- Jacoco maven plugin configuration properties -->
				<jacoco.includes/>
				<jacoco.excludes/>

				<jacoco.report.title>${project.name}</jacoco.report.title>
				<jacoco.report.footer>${project.name}</jacoco.report.footer>
				<jacoco.report.formats>HTML</jacoco.report.formats>

				<jacoco.rule.bundle.complexity.ratio>0.95</jacoco.rule.bundle.complexity.ratio>
				<jacoco.rule.bundle.branch.ratio>1</jacoco.rule.bundle.branch.ratio>
				<jacoco.rule.bundle.line.ratio>0.80</jacoco.rule.bundle.line.ratio>

				<jacoco.rule.class.line.ratio>0.80</jacoco.rule.class.line.ratio>
				<jacoco.rule.class.method.ratio>0.80</jacoco.rule.class.method.ratio>
			</properties>

			<build>
				<pluginManagement>
					<plugins>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-jar-plugin</artifactId>
							<executions>
								<execution>
									<id>jar-test</id>
									<goals>
										<goal>test-jar</goal>
									</goals>
								</execution>
							</executions>
						</plugin>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-surefire-plugin</artifactId>
							<executions>
								<execution>
									<id>unit-test</id>
									<goals>
										<goal>test</goal>
									</goals>
								</execution>
							</executions>
							<configuration>
								<includes>
									<include>**/*Tests.java</include>
								</includes>
								<excludes>
									<exclude>**/Abstract*.java</exclude>
								</excludes>
								<parallel>methods</parallel>
							</configuration>
						</plugin>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-failsafe-plugin</artifactId>
							<executions>
								<execution>
									<goals>
										<goal>integration-test</goal>
										<goal>verify</goal>
									</goals>
								</execution>
							</executions>
							<configuration>
								<includes>
									<include>**/*IntegrationTests.java</include>
								</includes>
								<excludes>
									<exclude>**/*Tests.java</exclude>
									<exclude>**/Abstract*.java</exclude>
								</excludes>
								<parallel>methods</parallel>
							</configuration>
						</plugin>
						<plugin>
							<groupId>org.jacoco</groupId>
							<artifactId>jacoco-maven-plugin</artifactId>
							<configuration>
								<includes>
									<include>${jacoco.includes}</include>
								</includes>
								<excludes>
									<exclude>${jacoco.excludes}</exclude>
									<!-- excludes all classes generated by Lombok -->
									<exclude>**/*_.class</exclude>
									<!-- excludes all inner classes -->
									<exclude>**/*$*.class</exclude>
									<exclude>**/*Dto.class</exclude>
									<exclude>**/*Entity.class</exclude>
									<exclude>**/*Config.class</exclude>
									<exclude>**/*Configuration.class</exclude>
								</excludes>
							</configuration>
							<executions>
								<!-- Unit Test Coverage -->
								<execution>
									<id>jacoco-prepare-initialize</id>
									<goals>
										<goal>prepare-agent</goal>
									</goals>
									<configuration>
										<destFile>${jacoco.destFile}</destFile>
										<append>true</append>
									</configuration>
								</execution>
								<!-- Integration Test Coverage -->
								<execution>
									<id>jacoco-prepare-integration-initialize</id>
									<goals>
										<goal>prepare-agent-integration</goal>
									</goals>
									<configuration>
										<destFile>${jacoco.destFile}</destFile>
										<append>true</append>
									</configuration>
								</execution>
								<!-- Generate Reports -->
								<execution>
									<id>jacoco-report</id>
									<phase>verify</phase>
									<goals>
										<goal>report</goal>
										<goal>report-integration</goal>
									</goals>
									<configuration>
										<dataFile>${jacoco.destFile}</dataFile>
										<outputDirectory>${jacoco.report.outputDirectory}</outputDirectory>
										<title>${jacoco.report.title}</title>
										<footer>${jacoco.report.footer}</footer>
										<formats>
											<format>${jacoco.report.formats}</format>
										</formats>
									</configuration>
								</execution>
								<!-- Check Coverage Rules -->
								<execution>
									<id>default-check</id>
									<phase>verify</phase>
									<goals>
										<goal>check</goal>
									</goals>
									<configuration>
										<dataFile>${jacoco.destFile}</dataFile>
										<rules>
											<!-- The main rule for the entire project -->
											<rule>
												<element>BUNDLE</element>
												<limits>
													<limit>
														<counter>COMPLEXITY</counter>
														<value>COVEREDRATIO</value>
														<minimum>${jacoco.rule.bundle.complexity.ratio}</minimum>
													</limit>
													<limit>
														<counter>BRANCH</counter>
														<value>COVEREDRATIO</value>
														<minimum>${jacoco.rule.bundle.branch.ratio}</minimum>
													</limit>
													<limit>
														<counter>LINE</counter>
														<value>COVEREDRATIO</value>
														<minimum>${jacoco.rule.bundle.line.ratio}</minimum>
													</limit>
												</limits>
												<excludes>
													<exclude>**/utils/**</exclude>
												</excludes>
											</rule>
											<!-- Separate rule for Utility classes -->
											<rule>
												<element>CLASS</element>
												<includes>
													<include>**/utils/**</include>
												</includes>
												<limits>
													<limit>
														<counter>LINE</counter>
														<value>COVEREDRATIO</value>
														<minimum>${jacoco.rule.class.line.ratio}</minimum>
													</limit>
													<limit>
														<counter>METHOD</counter>
														<value>COVEREDRATIO</value>
														<minimum>${jacoco.rule.class.method.ratio}</minimum>
													</limit>
												</limits>
											</rule>
										</rules>
									</configuration>
								</execution>
							</executions>
						</plugin>
					</plugins>
				</pluginManagement>

				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-jar-plugin</artifactId>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-failsafe-plugin</artifactId>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
					</plugin>
					<plugin>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
