<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>ir.artanpg.boot</groupId>
		<artifactId>artan-boot-dependencies</artifactId>
		<version>0.0.0-SNAPSHOT</version>
		<relativePath>../artan-boot-dependencies</relativePath>
	</parent>

	<artifactId>artan-boot-parent</artifactId>
	<packaging>pom</packaging>

	<name>artan-boot-parent</name>
	<description>Parent module for all modules in this project.</description>

	<properties>
		<argLine>-Xmx2048m</argLine>
		<threadCount>10</threadCount>
	</properties>

	<build>
		<defaultGoal>clean install</defaultGoal>

		<resources>
			<resource>
				<directory>${basedir}/src/main/resources</directory>
				<filtering>true</filtering>
				<excludes>
					<exclude>excludes/**</exclude>
				</excludes>
			</resource>
		</resources>
		<testResources>
			<testResource>
				<directory>${basedir}/src/test/resources</directory>
				<filtering>true</filtering>
				<excludes>
					<exclude>excludes/**</exclude>
				</excludes>
			</testResource>
		</testResources>

		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven-compiler-plugin.version}</version>
					<inherited>true</inherited>
					<configuration>
						<source>${java.version}</source>
						<target>${java.version}</target>
						<release>${java.version}</release>
						<parameters>true</parameters>
						<enablePreview>true</enablePreview>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>${maven-jar-plugin.version}</version>
					<inherited>true</inherited>
					<configuration>
						<archive>
							<addMavenDescriptor>false</addMavenDescriptor>
							<manifest>
								<addDefaultSpecificationEntries>false</addDefaultSpecificationEntries>
								<addDefaultImplementationEntries>false</addDefaultImplementationEntries>
							</manifest>
							<manifestEntries>
								<Built-By>Artan Programming Group</Built-By>
								<Implementation-Title>${project.name}</Implementation-Title>
								<Implementation-Version>${project.version}</Implementation-Version>
							</manifestEntries>
						</archive>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-source-plugin</artifactId>
					<version>${maven-source-plugin.version}</version>
					<inherited>true</inherited>
					<executions>
						<execution>
							<id>attach-sources</id>
							<phase>package</phase>
							<goals>
								<goal>jar-no-fork</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<version>${maven-javadoc-plugin.version}</version>
					<inherited>true</inherited>
					<configuration>
						<source>${java.version}</source>
					</configuration>
					<executions>
						<execution>
							<id>attach-javadocs</id>
							<phase>package</phase>
							<goals>
								<goal>jar</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>${maven-surefire-plugin.version}</version>
					<inherited>true</inherited>
					<executions>
						<execution>
							<id>unit-test</id>
							<goals>
								<goal>test</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
						<runOrder>alphabetical</runOrder>
						<includes>
							<include>**/*Tests.java</include>
						</includes>
						<excludes>
							<exclude>**/Abstract*.java</exclude>
						</excludes>
						<parallel>methods</parallel>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-enforcer-plugin</artifactId>
					<version>${maven-enforcer-plugin.version}</version>
					<inherited>true</inherited>
					<executions>
						<execution>
							<id>enforce-release</id>
							<goals>
								<goal>enforce</goal>
							</goals>
							<phase>validate</phase>
							<configuration>
								<rules>
									<requireJavaVersion>
										<version>[21,)</version>
										<message>At least your java version should be 21 !!!</message>
									</requireJavaVersion>
									<requireMavenVersion>
										<version>[3.9.0,)</version>
										<message>At least your maven version should be 3.9.0 or higher !!!</message>
									</requireMavenVersion>
									<banDuplicatePomDependencyVersions>
										<message>No duplicate dependencies allowed !!!</message>
									</banDuplicatePomDependencyVersions>
									<requireProperty>
										<property>project.name</property>
									</requireProperty>
									<requireProperty>
										<property>project.description</property>
									</requireProperty>
								</rules>
								<fail>true</fail>
							</configuration>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>flatten-maven-plugin</artifactId>
					<version>${flatten-maven-plugin.version}</version>
					<inherited>true</inherited>
					<executions>
						<execution>
							<!-- Tidy up all POMs before they are published -->
							<id>flatten</id>
							<phase>process-resources</phase>
							<goals>
								<goal>flatten</goal>
							</goals>
							<configuration>
								<updatePomFile>true</updatePomFile>
								<flattenMode>oss</flattenMode>
								<pomElements>
									<scm>remove</scm>
									<issueManagement>remove</issueManagement>
									<distributionManagement>remove</distributionManagement>
									<repositories>remove</repositories>
								</pomElements>
							</configuration>
						</execution>
						<execution>
							<id>flatten-clean</id>
							<phase>clean</phase>
							<goals>
								<goal>clean</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</pluginManagement>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
